// <auto-generated />
using System;
using EFGetStarted;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace EFGetStarted.Migrations
{
    [DbContext(typeof(PropertyContextSqlLite))]
    partial class PropertyContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.7");

            modelBuilder.Entity("EFGetStarted.CommuteTime", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int?>("PropertyID")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("TravelTimeCycling")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("TravelTimeDriving")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("TravelTimePublicTransport")
                        .HasColumnType("INTEGER");

                    b.HasKey("ID");

                    b.HasIndex("PropertyID");

                    b.ToTable("PostCommuteTimes");
                });

            modelBuilder.Entity("EFGetStarted.Property", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.HasKey("ID");

                    b.ToTable("Properties");
                });

            modelBuilder.Entity("EFGetStarted.CommuteTime", b =>
                {
                    b.HasOne("EFGetStarted.Property", null)
                        .WithMany("CommuteTimes")
                        .HasForeignKey("PropertyID");
                });
#pragma warning restore 612, 618
        }
    }
}
